version: "3.8"
services:
  db:
    restart: always
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    restart: always
    image: etherpad/etherpad:1.8
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  api:
    restart: always
    depends_on:
      - db
    build:
      dockerfile: DockerfileApi
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api:ro
  front:
    restart: always
    depends_on:
      - api
    build:
      dockerfile: DockerfileFront
    ports:
       - "4200:4200"
    volumes:
      - ./front:/front
