version: "3.8"
services:
  reverse_proxy:
      image: traefik:2.5
      restart: unless-stopped
      ports:
        # The HTTP port
        - "80:80"
        # The HTTPS port
        - "443:443"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`tlc.loinvoyant.com`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=DwtQ65q4CqU8s6EQ:$$2y$$05$$6SVnbbYYCr23cC2WQDUFk.anS/p9lhkZWiUOmyCuN.6pgQx61H0dq"
      volumes:
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock
        # traefik static configuration
        - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
        # custom folder with dynamic configuration
        - ./custom:/etc/traefik/custom:ro
        # ssl volumes to store acme.json
        - ./certs:/letsencrypt
        #- ./providers:/providers
        #- ./passwd:/passwd
      networks:
        - web

volumes:
  certs:

networks:
  web:
    name: traefik_web
