version: "3.8"
services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'tlc'
      MYSQL_USER: 'tlc'
      MYSQL_PASSWORD: 'tlc'
    ports:
      - 3306:3306
    volumes: 
      - ./data:/var/lib/mysql

  phpmyadmin:
    restart: unless-stopped
    depends_on:
      - db
    image: phpmyadmin:latest
    networks:
      - traefik_web
    environment:
      PMA_HOST: 'db.tlc.loinvoyant.com'
      PMA_PORT: '3306'
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.phpmyadmin.entrypoints: websecure
      traefik.http.routers.phpmyadmin.rule: "Host(`phpmyadmin.tlc.loinvoyant.com`)"


networks:
  traefik_web:
    external: true