version: "3.8"
services:
  front:
    restart: always
    container_name: front
    build: ./
    volumes:
      - ./:/front
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.api.entrypoints: websecure
    ports:
      - 4200:4200