version: "3.8"
services:
  front:
    restart: always
    build: ./
    volumes:
      - ./:/front
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.front.entrypoints: websecure
      traefik.http.routers.front.rule: "Host(`front.tlc.loinvoyant.com`)"
      traefik.http.services.front.loadbalancer.server.port: 4200 