version: "3.8"
services:
  api:
    restart: always
    build: ./
    volumes:
      - ./:/api:ro
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.api.entrypoints: api
      traefik.http.routers.api.rule: "Host(`api.tlc.loinvoyant.com`)"
      traefik.http.services.api.loadbalancer.server.port: 8080 