version: "3.8"
services:
  api:
    container_name: api
    restart: always
    build: ./
    volumes:
      - ./:/api:ro
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.api.entrypoints: websecure
    ports:
      - 8080:8080